require 'spec_helper'


# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Admin::PartsController do
  fixtures :parts
  # This should return the minimal set of attributes required to create a valid
  # Part. As you add validations to Admin::Part, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  Factory.define :part do |part|
    part.name "Transmissao"
    part.description "Transmissao"
  end
  describe "GET index" do
    it "assigns all admin_parts as @admin_parts" do
      # part = Part.create! valid_attributes
      get :index
      assigns(:parts).should eq(Part.all)
    end
  end

  describe "GET show" do
    it "assigns the requested admin_part as @admin_part" do
      part = Factory(:part)
      get :show, :id => part.id.to_s
      assigns(:part).should eq(part)
    end
  end

  describe "GET new" do
    it "assigns a new admin_part as @admin_part" do
      get :new
      assigns(:part).should be_a_new(Part)
    end
  end

  describe "GET edit" do
    it "assigns the requested admin_part as @admin_part" do
      part = Factory(:part)
      get :edit, :id => part.id.to_s
      assigns(:part).should eq(part)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Admin::Part" do
        expect {
          post :create, :part => valid_attributes
        }.to change(Part, :count).by(1)
      end

      it "assigns a newly created admin_part as @admin_part" do
        post :create, :part => valid_attributes
        assigns(:part).should be_a(Part)
        assigns(:part).should be_persisted
      end

      it "redirects to the created admin_part" do
        post :create, :part => valid_attributes
        response.should redirect_to(admin_part_path(Part.last))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved admin_part as @admin_part" do
        # Trigger the behavior that occurs when invalid params are submitted
        Part.any_instance.stub(:save).and_return(false)
        post :create, :part => {}
        assigns(:part).should be_a_new(Part)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Part.any_instance.stub(:save).and_return(false)
        post :create, :part => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested admin_part" do
        part = Part.create! valid_attributes
        # Assuming there are no other admin_parts in the database, this
        # specifies that the Admin::Part created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Part.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => part.id, :part => {'these' => 'params'}
      end

      it "assigns the requested admin_part as @admin_part" do
        part = Factory(:part)
        put :update, :id => part.id, :part => Factory(:part)
        assigns(:part).should eq(part)
      end

      it "redirects to the admin_part" do
        part = Part.create! valid_attributes
        put :update, :id => part.id, :part => valid_attributes
        response.should redirect_to(admin_part_path(part))
      end
    end

    describe "with invalid params" do
      it "assigns the admin_part as @admin_part" do
        part = Part.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Part.any_instance.stub(:save).and_return(false)
        put :update, :id => part.id.to_s, :part => {}
        assigns(:part).should eq(part)
      end

      it "re-renders the 'edit' template" do
        part = Part.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Part.any_instance.stub(:save).and_return(false)
        put :update, :id => part.id.to_s, :part => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested admin_part" do
      part = Part.create! valid_attributes
      expect {
        delete :destroy, :id => part.id.to_s
      }.to change(Part, :count).by(-1)
    end

    it "redirects to the admin_parts list" do
      part = Part.create! valid_attributes
      delete :destroy, :id => part.id.to_s
      response.should redirect_to(admin_parts_url)
    end
  end

end
